#!/usr/bin/env bash

pushd `dirname $0` > /dev/null 2>&1;


# find path to php
PHP_BIN=`which php`
if [ -z "$PHP_BIN" ]; then
	echo 'PHP executable not found, enter path: '
	read PHP_BIN
fi


# run pre-install.php
if [ -x "$PHP_BIN" ]; then
	$PHP_BIN ./pre-install.php
else
	echo 'PHP executable not found, unable to run pre-install.php'
	exit 1;
fi


popd > /dev/null 2>&1;
exit 0;
